### ISSUE TITLE
[1.7.10] Capacitor Seeds are Not Considered Seeds According to MineTweaker

### ISSUE THREAD

**Issue by Whimsyturtle** [HenryLoenwind/EnderIOAddons#42]
I Setup a Basic AgriCraft Minetweaker Script to Replace the Base Block of Bedrock to Septuple Compressed Cobblestone

Script:
import mods.agricraft.growing.BaseBlock;
BaseBlock.clear(<enderioaddons:itemMachineParts:22>);
BaseBlock.set(<enderioaddons:itemMachineParts:22>, <ExtraUtilities:cobblestone_compressed:6>, 1);

An Error was Generated:
[Client thread/INFO]: [CHAT] ERROR: Error executing AgriCraft.zs: info.loenwind.enderioaddons.machine.part.ItemMachinePart cannot be cast to net.minecraft.item.ItemSeeds
[Client thread/INFO]: [CHAT] ERROR: Error executing AgriCraft.zs: info.loenwind.enderioaddons.machine.part.ItemMachinePart cannot be cast to net.minecraft.item.ItemSeeds

I Even Added Ore Dictionaries to the Seed, 2nd Script:
var listAllseed = <ore:listAllseed>;
var seedCapacitor = <ore:seedCapacitor>;
listAllseed.add(<enderioaddons:itemMachineParts:22>);
seedCapacitor.add(<enderioaddons:itemMachineParts:22>);

And Reloaded the Game,

Still No Effect.

**Comment by HenryLoenwind** [comment]
Known issue with Agricraft. Use the Ender IO Addons configuration to change the block.

**Comment by spannerman79** [comment]
For reference (in case anyone else searches like I have) to change it to Extra Utilities compressed cobble it's in the following format;

`ExtraUtilities:cobblestone_compressed@x` where `x` is the last number when you use `/mt hand` when holding the compressed cobble in hand minus 1

So if you wish to use 8x the block meta value is `ExtraUtilities:cobblestone_compressed@7`

This might be helpful for someone else instead of doing trial/error like I did
