### ISSUE TITLE
NoSuchMethodError (SMP)

### ISSUE THREAD

**Issue by jburrows82** [HenryLoenwind/EnderIOAddons#7]
Just updated to 0.9.3

http://pastebin.com/E5fHxdtv

**Comment by HenryLoenwind** [comment]
Already uploaded 0.9.4 ;)

**Comment by jburrows82** [comment]
Updated to 0.9.4 ... and same error.

http://pastebin.com/fH4NHENp

Sorry! =)

**Comment by HenryLoenwind** [comment]
nope, that "sorry" is my line here. I had already seen two crash reports for 0.9.3 and didn't even look at yours, assuming it was the same. But is wasn't.

Root cause: Github Desktop software likes to switch branches on its own from time to time, so my first "what happens when I poke here?" tries for the rancher ended up in the release instead of the testing branch.

New version is uploaded.
